name: deploy-to-server
on: 
  push:
    branches:
      -main
      -master
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Started deployment!'
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-some-placeholder-value'
      - name: Adding known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy with Rsync
        run: rsync -avz ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/jelly/public/
        
