name: deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: WHAT IS DIR??
        run: pwd
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
     
      - name: Test ssh
        run: echo ${{ secrets.SSH_PRIVATE_KEY }} | sudo tee key.txt \
          chmod 600 ./key.txt \
          ssh -i  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
#       - name: Deploy with rsync
#         uses: Burnett01/rsync-deployments@5.2.1
#         with:
#           switches: -avPO
#           path: public/
#           remote_path: /var/www/jelly/public
#           remote_host: ${{ secrets.SSH_HOST }}
#           remote_user: ${{ secrets.SSH_USER }}
#           remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
