name: deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: WHAT IS DIR??
        run: pwd
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
        
      - name: Check connection
        run: curl -v telnet://${{ secrets.SSH_HOST }}:443

      - name: Deploy with rsync
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avPO --delete
          path: public/
          remote_path: /var/www/jelly/public
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
